#!/bin/bash
cp -r ~/.config/zsh ~/.alice/config/
cp ~/.zshrc ~/.alice/config/zsh/zshrc
cp ~/.tmux.conf ~/.alice/config/tmux.conf

cp -r ~/.config/uwsm/ ~/.alice/config/
cp -r ~/.config/kitty ~/.alice/config/
cp -r ~/.config/fastfetch/ ~/.alice/config/
cp -r ~/.config/btop ~/.alice/config/
cp -r ~/.config/environment.d ~/.alice/config/
cp -r ~/.config/fcitx5 ~/.alice/config/
cp -r ~/.config/fontconfig ~/.alice/config/
cp -r ~/.config/imv ~/.alice/config/
cp -r ~/.config/swayosd ~/.alice/config/
cp -r ~/.config/systemd ~/.alice/config/
cp -r ~/.config/uwsm ~/.alice/config/
cp -r ~/.config/walker ~/.alice/config/

cp -r ~/.config/starship.toml ~/.alice/config/
