#!/bin/bash
cp -r ~/.config/hypr ~/.alice/config/

cp -r ~/.config/quickshell/ ~/.alice/config/
rm -rf ~/.alice/config/quickshell/.git

cp -r ~/.config/bash ~/.alice/config/
cp ~/.bashrc ~/.alice/config/bash/bashrc

cp -r ~/.config/uwsm/ ~/.alice/config/

cp -r ~/.config/kitty ~/.alice/config/

cp -r ~/.config/kitty ~/.alice/config/

cp -r ~/.config/fastfetch/ ~/.alice/config/
