[ids]
*

[main]
capslock = overload(capslock, esc)
# esc = noop
rightalt = layer(meta)

[capslock:C]
h = left
k = up
j = down
l = right

[capslock+shift]
h = volumedown
j = brightnessdown
k = brightnessup
l = volumeup
