# Background and foreground colors
background = #0e0e11
foreground = #faf9fa

# Standard colors
palette = 0=#0e0e11
palette = 1=#ce7eac
palette = 2=#95bbdd
palette = 3=#d49cdf
palette = 4=#7b75d6
palette = 5=#bd86d1
palette = 6=#7e9cce
palette = 7=#faf9fa

# Bright colors
palette = 8=#9b9bb0
palette = 9=#e1b0cd
palette = 10=#afcee9
palette = 11=#dfafe9
palette = 12=#7671db
palette = 13=#d7b5e3
palette = 14=#7b9bd0
palette = 15=#faf9fa
