background            #0e0e11
foreground            #faf9fa

# black
color0  #0e0e11
color8  #9b9bb0

# red
color1  #ce7eac
color9  #e1b0cd

# green
color2  #95bbdd
color10 #afcee9

# yellow
color3  #d49cdf
color11 #dfafe9

# blue
color4  #7b75d6
color12 #7671db

# magenta
color5  #bd86d1
color13 #d7b5e3

#cyan
color6  #7e9cce
color14 #7b9bd0

#white
color7  #faf9fa
color15 #faf9fa


