name: Aether
accent: "#7b75d6"
cursor: "#7b75d6"
background: "#0e0e11"
foreground: "#faf9fa"
details: darker

terminal_colors:
  normal:
    black:   "#0e0e11"
    red:     "#ce7eac"
    green:   "#95bbdd"
    yellow:  "#d49cdf"
    blue:    "#7b75d6"
    magenta: "#bd86d1"
    cyan:    "#7e9cce"
    white:   "#faf9fa"
  bright:
    black:   "#9b9bb0"
    red:     "#e1b0cd"
    green:   "#afcee9"
    yellow:  "#dfafe9"
    blue:    "#7671db"
    magenta: "#d7b5e3"
    cyan:    "#7b9bd0"
    white:   "#faf9fa"
