#!/usr/bin/bash

# install nvim

echo "Cloning kickstart.nvim..."
git clone "https://github.com/neros29/kickstart.nvim.git"

if [ -d "$HOME/.config/nvim" ] && [ "$(ls -A "$HOME/.config/nvim")" ]; then
    echo "Error: '$HOME/.config/nvim' is not empty. Move aborted to prevent overwriting files."
else
    echo "Target '$HOME/.config/nvim' is empty or doesn't exist. Moving files..."
    mkdir -p "$HOME/.config/nvim"
    cp -r kickstart.nvim/* "$HOME/.config/nvim"
    rm -rf kickstart.nvim
    echo "Successfully installed kickstart.nvim to '$HOME/.config/nvim'"
fi

# install hypr configs

# install quickshell configs
