# Fonts
font_family JetBrains Mono
italic_font              auto
bold_italic_font         auto
font_size                10
disable_ligatures        never

# Performance / behavior
scrollback_lines         20000

detect_urls              yes
copy_on_select           no
strip_trailing_spaces    smart
shell_integration        enabled

# remote contorl
allow_remote_control     yes
listen_on                unix:/tmp/kitty

# Wayland/scroll behavior
macos_option_as_alt      yes
mouse_hide_wait          2.0

